name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
   

      
    - name : ssh to server
      run: |
            cd ~
            touch private.pem
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > private.pem
            chmod 777 private.pem
            cat private.pem
            echo "mesh Hello1dd"
            cd ~
            mkdir .ssh
            chmod 777 .ssh 
            touch .ssh/known_hosts
            cd .ssh
            chmod 777 known_hosts 
            ssh-keyscan -t rsa 54.197.85.238 >> ~/.ssh/known_hosts
            cd ~
            echo "mesh akher  Hello1dd"
            
            sudo ssh -i private.pem ubuntu@54.197.85.238 
            
      shell: bash
      
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "/home/ubuntu/node_hosting_on_EC2"
        REMOTE_HOST: 54.197.85.238
        REMOTE_USER: ubuntu
        TARGET: "/var/www/html/"
