name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Add host key
      run: ssh-keyscan 54.197.85.238  >> $HOME/.ssh/known_hosts
 
      
    - name : ssh to server
      run: |
            cd ~
            touch private.pem
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > private.pem
            chmod 777 private.pem
            cat private.pem
            echo "mesh Helldo1dd"
            cd ~
            mkdir .ssh
            cd .ssh
            touch known_hosts
            chmod 777 known_hosts
            cd ~
            echo "${{ secrets.KNOWN_HOSTS }}" >> ~/.ssh/known_hosts
            cd ~
            echo "mesh akher  Hello1dd"
            sudo ssh -i private.pem ubuntu@54.197.85.238 
            
      shell: bash
      
    - name: Deploy to EC2
      uses: appleboy/scp-action@master
      env:
        KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "/home/ubuntu/node_hosting_on_EC2"
        REMOTE_HOST: 54.197.85.238
        REMOTE_USER: ubuntu
        TARGET: "/var/www/html/"
