name: Deploy to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
  
      
    - name : ssh to server and do the whole deployment
      run: |
            cd ~
            cat node_hosting_on_EC2/front-end/jony-master/index.html
            sudo scp -r node_hosting_on_EC2 /var/www
            sudo systemctl restart nginx
      shell: bash
      
